garmin_agl: # namespace of the agl estimator
  requires: # data required from the hw api
    gnss: false
    imu: false
    distance_sensor: true
    altitude: false
    magnetometer_heading: false
    position: false
    orientation: false
    velocity: false
    angular_velocity: false

  garmin_agl: # namespace of the agl estimator
    max_flight_z: 10.0 # [m] maximum allowed flight Z (in the estimator frame)

    innovation:
      limit: 5.0 # [m] innovation limit that will trigger action
      action: "switch" # {"eland", "switch", "mitigate"}

    repredictor: # repredictor for correct fusion of delayed measurements
      enabled: false

    process_noise: # process noise covariance (Q)
      pos: 1.0 # position state
      vel: 1.0 # velocity state
      acc: 1.0 # acceleration state

    corrections: [
      "pos_garmin"
    ]

    pos_garmin:
      state_id: 0 # 0 - position, 1 - velocity, 2 - acceleration
      noise: 0.1 # measurement noise covariance (R)
      noise_unhealthy_coeff: 100.0 # covariance gets multiplied by this coefficient when correction is unhealthy (R)
      message:
        type: "sensor_msgs/Range"
        topic: "hw_api/distance_sensor" # without uav namespace
        limit: 
          delay: 1.0 # [s] messages with higher delay will flag correction as unhealthy
          time_since_last: 1.0 # [s] larger time step between messages will flag correction as unhealthy

      processors: [] # types of processors attached to this measurement


