hector_garmin: # namespace of the state estimator
  hdg_hector: # namespace of the heading estimator

    max_flight_z: 10.0 # [m] maximum allowed flight Z (in the estimator frame)

    repredictor: # repredictor for correct fusion of delayed measurements
      enabled: true
      buffer_size: 200 # [samples] how many states and corrections are kept in history (i.e. estimator running at the default 100 Hz rate will be able to fuse corrections with up to 2 s delay with buffer size of 200 samples)

    process_noise: # process noise covariance (Q)
      pos: 0.1 # position state
      vel: 0.1 # velocity state

    corrections: [
      "hdg_hector"
    ]

    hdg_hector:
      state_id: 0 # 0 - position, 1 - velocity, 2 - acceleration
      noise: 0.0001 # measurement noise covariance (R)
      message:
        type: "geometry_msgs/PoseStamped"
        topic: "hector_mapping/slam_out_pose" # without uav namespace
        limit: 
          delay: 2.0 # [s] messages with higher delay will flag correction as unhealthy
          time_since_last: 1.0 # [s] larger time step between messages will flag correction as unhealthy

      processors: [] # types of processors attached to this measurement
