mrs_uav_managers:
  estimation_manager:
    hector_garmin: # namespace of the state estimator
      override_frame_id: # override the default frame_id with a custom one (e.g. slam_origin instead of aloam_origin)
        enabled: false
        frame_id: "hector_origin" # the desired frame_id without the UAV namespace





