# standalone height estimator
estimation_manager: # namespace
  est_alt_agl: # namespace of the altitude estimator

    max_flight_altitude_agl: 10.0 # [m] maximum allowed flight altitude AGL (Above Ground Level)

    repredictor: # repredictor for correct fusion of delayed measurements
      enabled: false

    process_noise: # process noise covariance (Q)
      pos: 1.0 # position state
      vel: 1.0 # velocity state
      acc: 1.0 # acceleration state

    corrections: [
      "pos_garmin"
    ]

    pos_garmin:
      state_id: 0 # 0 - position, 1 - velocity, 2 - acceleration
      noise: 1.0 # measurement noise covariance (R)
      message:
        type: 3 # 0 - nav_msgs/Odometry, 1 - geometry_msgs/PoseStamped, 2 - geometry_msgs/PoseWithCovarianceStamped, 3 - sensor_msgs/Range
        topic: "garmin/range" # without uav namespace
        limit: 
          delay: 0.5 # [s] messages with higher delay will flag correction as unhealthy
          time_since_last: 0.5 # [s] larger time step between messages will flag correction as unhealthy

      processors: [] # types of processors attached to this measurement

