mrs_uav_managers:
  estimation_manager:
    ground_truth:
      max_flight_z: 100.0 # [m] maximum allowed flight Z (in the estimator frame)

      message:
        topic: "hw_api/ground_truth"

      requires: # data required from the hw api
        gnss: false
        rtk: false
        imu: false
        distance_sensor: false
        altitude: false
        magnetometer_heading: false
        position: false
        orientation: false
        velocity: false
        angular_velocity: false
        ground_truth: true
