# passthrough estimator - no estimation on its own
gps_baro: # namespace of the state estimator
  hdg_mavros: # namespace of the heading estimator

    max_flight_altitude_agl: 100.0 # [m] maximum allowed flight altitude AGL (Above Ground Level)

    message:
      topic: "hw_api/orientation" # without uav namespace
