mrs_uav_managers:
  estimation_manager:
    gps_baro: # namespace of the state estimator
      requires: # data required from the hw api
        gnss: true
        imu: false
        distance_sensor: false
        altitude: true
        magnetometer_heading: false
        position: true
        orientation: true
        velocity: true
        angular_velocity: true

      estimators: # the names of the partial estimators
        lateral:
          name: "lat_gps"
        altitude:
          name: "alt_baro"
        heading:
          name: "hdg_hw_api"
          passthrough: true # if true, then heading is not estimated but passed through from the orientation topic

      topics:
        orientation: "hw_api/orientation" # orientation passthrough
        angular_velocity: "hw_api/angular_velocity" # angular velocity passthrough
