gps_garmin: # namespace of the state estimator
  alt_garmin: # namespace of the altitude estimator

    process_noise: # process noise covariance (Q)
      pos: 1.0 # position state
      vel: 1.0 # velocity state
      acc: 1.0 # acceleration state

    corrections: [
      "pos_garmin",
      "vel_baro"
    ]

    pos_garmin:
      state_id: 0 # 0 - position, 1 - velocity, 2 - acceleration
      noise: 1.0 # measurement noise covariance (R)
      message:
        type: 3 # 0 - nav_msgs/Odometry, 1 - geometry_msgs/PoseStamped, 2 - geometry_msgs/PoseWithCovarianceStamped, 3 - sensor_msgs/Range
        topic: "garmin/range" # without uav namespace
        limit: 
          delay: 0.5 # [s] messages with higher delay will flag correction as unhealthy
          time_since_last: 0.5 # [s] larger time step between messages will flag correction as unhealthy

    vel_baro:
      state_id: 1 # 0 - position, 1 - velocity, 2 - acceleration
      noise: 1.0 # measurement noise covariance (R)
      message:
        type: 0 # 0 - nav_msgs/Odometry, 1 - geometry_msgs/PoseStamped, 2 - geometry_msgs/PoseWithCovarianceStamped, 3 - sensor_msgs/Range
        topic: "mavros/local_position/odom" # without uav namespace
        limit: 
          delay: 1.0 # [s] messages with higher delay will flag correction as unhealthy
          time_since_last: 0.5 # [s] larger time step between messages will flag correction as unhealthy
