gps_garmin: # namespace of the state estimator
  requires: # data required from the hw api
    gnss: true
    imu: false
    distance_sensor: true
    altitude: false
    magnetometer_heading: false
    position: true
    orientation: true
    velocity: true
    angular_velocity: false

  orientation_topic: "hw_api/orientation" # without uav namespace




