gps_garmin: # namespace of the state estimator
  requires: # data required from the hw api
    gnss: true
    imu: false
    distance_sensor: true
    altitude: false
    magnetometer_heading: false
    position: true
    orientation: true
    velocity: true
    angular_velocity: true

  estimators: # the names of the partial estimators
    lateral:
      name: "lat_gps"
    altitude:
      name: "alt_garmin"
    heading:
      name: "hdg_hw_api"
      passthrough: true # if true, then heading is not estimated but passed through from the orientation topic

  topics:
    orientation: "hw_api/orientation" # orientation passthrough
    angular_velocity: "hw_api/angular_velocity" # angular velocity passthrough

  override_frame_id:
    enabled: false # if true, custom frame_id can be provided instead of the default "[estimator_name]_origin"
    frame_id: ""




