gps_garmin: # namespace of the state estimator
  requires: # data required from the hw api
    gnss: true
    imu: false
    distance_sensor: true
    altitude: false
    magnetometer_heading: false
    position: true
    orientation: true
    velocity: true
    angular_velocity: true

  topics:
    orientation: "hw_api/orientation" # orientation passthrough
    angular_velocity: "hw_api/angular_velocity" # angular velocity passthrough




