gps_garmin: # namespace of the state estimator
  lat_gps: # namespace of the lateral estimator

    max_flight_altitude_agl: 100.0 # [m] maximum allowed flight altitude AGL (Above Ground Level)

    hdg_source_topic: "gps_garmin/hdg_hw_api/output" # [mrs_uav_state_estimation/EstimatorOutput]

    repredictor: # repredictor for correct fusion of delayed measurements
      enabled: false

    process_noise: # process noise covariance (Q)
      # pos: 1 # position state
      # vel: 10 # velocity state
      # acc: 0.01 # acceleration state
      pos: 0.1 # position state
      vel: 1 # velocity state
      acc: 1 # acceleration state

    corrections: [
      "pos_hw_api"
    ]

    pos_hw_api:
      state_id: 0 # 0 - position, 1 - velocity, 2 - acceleration
      noise: 0.01 # measurement noise covariance (R)
      message:
        type: "geometry_msgs/PointStamped"
        topic: "hw_api/position" # without uav namespace
        limit: 
          delay: 0.5 # [s] messages with higher delay will flag correction as unhealthy
          time_since_last: 0.5 # [s] larger time step between messages will flag correction as unhealthy

      processors: ["tf_to_world"] # types of processors attached to this measurement

      tf_to_world:
        gnss_topic: "hw_api/gnss"

