gps_garmin: # namespace of the state estimator
  lat_gps: # namespace of the lateral estimator

    max_flight_altitude_agl: 100.0 # [m] maximum allowed flight altitude AGL (Above Ground Level)

    hdg_source_topic: "gps_garmin/hdg_mavros/output" # [mrs_uav_state_estimation/EstimatorOutput]

    repredictor: # repredictor for correct fusion of delayed measurements
      enabled: false

    process_noise: # process noise covariance (Q)
      pos: 0.001 # position state
      vel: 1.0 # velocity state
      acc: 0.01 # acceleration state

    corrections: [
      "pos_mavros"
    ]

    pos_mavros:
      state_id: 0 # 0 - position, 1 - velocity, 2 - acceleration
      noise: 1.0 # measurement noise covariance (R)
      message:
        type: 0 # 0 - nav_msgs/Odometry, 1 - geometry_msgs/PoseStamped, 2 - geometry_msgs/PoseWithCovarianceStamped, 3 - sensor_msgs/Range
        topic: "mavros/local_position/odom" # without uav namespace
        limit: 
          delay: 0.5 # [s] messages with higher delay will flag correction as unhealthy
          time_since_last: 0.5 # [s] larger time step between messages will flag correction as unhealthy
