gps_garmin:
  address: "mrs_uav_state_estimation/GpsGarmin"
rtk:
  address: "mrs_uav_state_estimation/Rtk"
aloam:
  address: "mrs_uav_state_estimation/Aloam"
ground_truth:
  address: "mrs_uav_state_estimation/GroundTruth"
dummy:
  address: "mrs_uav_state_estimation/Dummy"
