version: "0.0.0.1"

# names of used frames are specified here
frame_id:
  fcu: "fcu" # the body frame of the UAV where the flight control unit resides (default: "fcu")
  fcu_untilted: "fcu_untilted" # the body frame with zero tilt angles default: ("fcu_untilted")
  rtk_antenna: "rtk_antenna" # the body frame with zero tilt angles default: ("fcu_untilted")

# loaded state estimator plugins
state_estimators: [
"gps_garmin",
# "gps_baro",
# "rtk",
# "aloam",
"ground_truth",
# "dummy"
]

initial_estimator: "gps_garmin" # will be used as the first estimator

# rates of timers [Hz]
rate:
  uav_state: 100 # used by the control_manager for feedback control (default: 100)
  health: 100 # checks if everything is ok (default: 100)

