version: "0.0.0.1"

local_origin_tf:
  enabled: true # local_origin tf should be published by default unless some other node already publishes it
  parent: "fcu" # fcu should be the parent if using the default inverted mrs tf tree convention with fcu as the root of the tf tree
  # child: "local_origin"
  child: "local_origin_tmp"

stable_origin_tf:
  enabled: true # stable_origin tf should be published by default unless some other node already publishes it
  parent: "fcu" # fcu should be the parent if using the default inverted mrs tf tree convention with fcu as the root of the tf tree
  # child: "stable_origin"
  child: "stable_origin_tmp"

fixed_origin_tf:
  enabled: true # fixed_origin tf should be published by default unless some other node already publishes it
  parent: "fcu" # fcu should be the parent if using the default inverted mrs tf tree convention with fcu as the root of the tf tree
  # child: "fixed_origin"
  child: "fixed_origin_tmp"

fcu_untilted_tf:
  enabled: true # fcu_untilted tf should be published by default unless some other node already publishes it
  parent: "fcu" # fcu should be the parent if using the default inverted mrs tf tree convention with fcu as the root of the tf tree
  # child: "fcu_untilted"
  child: "fcu_untilted_tmp"

# the list of source topics from which the tfs will be constructed 
tf_sources: ["gps_garmin", "rtk", "aloam", "ground_truth"]

# odom_main:
#   topic: "odom_main" # name of the topic (expects nav_msgs/Odometry topic type)
#   namespace: "estimation_manager" # the namespace of the topic (usually the node that publishes the topic)
#   utm_based: false # if true, will publish tf to utm_origin
#   inverted: true # publish as inverted tf (the default for inverted mrs tf tree convention)
#   republish_in_frames: ["local_origin"] # the odometry message will be transformed and republished in the specified frames

gps_garmin:
  topic: "odom" # name of the topic (expects nav_msgs/Odometry topic type)
  namespace: "estimation_manager/gps_garmin" # the namespace of the topic (usually the node that publishes the topic)
  utm_based: true # if true, will publish tf to utm_origin
  in_utm: false # if true, the coordinates of the tf source are already in utm_origin
  inverted: true # publish as inverted tf (the default for inverted mrs tf tree convention)
  republish_in_frames: ["local_origin"] # the odometry message will be transformed and republished in the specified frames

rtk:
  topic: "odom" # name of the topic (expects nav_msgs/Odometry topic type)
  namespace: "estimation_manager/rtk" # the namespace of the topic (usually the node that publishes the topic)
  utm_based: true # if true, will publish tf to utm_origin
  in_utm: true # if true, the coordinates of the tf source are already in utm_origin
  inverted: true # publish as inverted tf (the default for inverted mrs tf tree convention)
  republish_in_frames: ["local_origin"] # the odometry message will be transformed and republished in the specified frames

aloam:
  topic: "odom" # name of the topic (expects nav_msgs/Odometry topic type)
  namespace: "estimation_manager/aloam" # the namespace of the topic (usually the node that publishes the topic)
  utm_based: false # if true, will publish tf to utm_origin
  inverted: true # publish as inverted tf (the default for inverted mrs tf tree convention)
  republish_in_frames: ["local_origin"] # the odometry message will be transformed and republished in the specified frames

ground_truth:
  topic: "odom" # name of the topic (expects nav_msgs/Odometry topic type)
  namespace: "estimation_manager/ground_truth" # the namespace of the topic (usually the node that publishes the topic)
  utm_based: false # if true, will publish tf to utm_origin
  inverted: true # publish as inverted tf (the default for inverted mrs tf tree convention)
  republish_in_frames: ["local_origin"] # the odometry message will be transformed and republished in the specified frames
