version: "0.0.0.1"

fcu_untilted_tf:
  enabled: false # fcu_untilted tf should be published by default unless some other node already publishes it
  parent: "fcu" # fcu should be the parent if using the default inverted mrs tf tree convention with fcu as the root of the tf tree
  child: "fcu_untilted"

# the list of source topics from which the tfs will be constructed 
tf_sources: ["odom_main", "gps_garmin", "rtk", "aloam"]

odom_main:
  topic: "odom_main" # name of the topic (expects nav_msgs/Odometry topic type)
  namespace: "estimation_manager" # the namespace of the topic (usually the node that publishes the topic)
  utm_based: false # if true, will publish tf to utm_origin
  inverted: true # publish as inverted tf (the default for inverted mrs tf tree convention)
  republish_in_frames: ["local_origin"] # the odometry message will be transformed and republished in the specified frames

gps_garmin:
  topic: "odom" # name of the topic (expects nav_msgs/Odometry topic type)
  namespace: "estimation_manager/gps_garmin" # the namespace of the topic (usually the node that publishes the topic)
  utm_based: true # if true, will publish tf to utm_origin
  in_utm: false # if true, the coordinates of the tf source are already in utm_origin
  inverted: true # publish as inverted tf (the default for inverted mrs tf tree convention)
  republish_in_frames: ["local_origin"] # the odometry message will be transformed and republished in the specified frames

rtk:
  topic: "odom" # name of the topic (expects nav_msgs/Odometry topic type)
  namespace: "estimation_manager/rtk" # the namespace of the topic (usually the node that publishes the topic)
  utm_based: true # if true, will publish tf to utm_origin
  in_utm: true # if true, the coordinates of the tf source are already in utm_origin
  inverted: true # publish as inverted tf (the default for inverted mrs tf tree convention)
  republish_in_frames: ["local_origin"] # the odometry message will be transformed and republished in the specified frames

aloam:
  topic: "odom" # name of the topic (expects nav_msgs/Odometry topic type)
  namespace: "estimation_manager/aloam" # the namespace of the topic (usually the node that publishes the topic)
  utm_based: false # if true, will publish tf to utm_origin
  inverted: true # publish as inverted tf (the default for inverted mrs tf tree convention)
  republish_in_frames: ["local_origin"] # the odometry message will be transformed and republished in the specified frames
