vio: # namespace of the state estimator
  requires: # data required from the hw api
    gnss: false
    imu: false
    distance_sensor: false
    altitude: false
    magnetometer_heading: false
    position: false
    orientation: true
    velocity: true
    angular_velocity: true

  estimators: # the names of the partial estimators
    lateral:
      name: "lat_vio"
    altitude:
      name: "alt_vio"
    heading:
      name: "hdg_vio"
      passthrough: false # if true, then heading is not estimated but passed through from the orientation topic

  topics:
    orientation: "hw_api/orientation" # orientation passthrough
    angular_velocity: "hw_api/angular_velocity" # angular velocity passthrough

  override_frame_id: # override the default frame_id with a custom one (e.g. slam_origin instead of vio_origin)
    enabled: false
    frame_id: "vio_origin" # the desired frame_id without the UAV namespace





