mrs_uav_managers:
  estimation_manager:
    rtk: # namespace of the state estimator
      alt_rtk: # namespace of the altitude estimator

        max_flight_z: 100.0 # [m] maximum allowed flight Z (in the estimator frame)

        innovation:
          limit: 1.0 # [m] innovation limit that will trigger action
          action: "mitigate" # {"eland", "switch", "mitigate"}

        repredictor: # repredictor for correct fusion of delayed measurements
          enabled: false

        process_noise: # process noise covariance (Q)
          pos: 1.0 # position state
          vel: 1.0 # velocity state
          acc: 1.0 # acceleration state

        corrections: [
          "pos_rtk",
          "vel_hw_api"
        ]

        pos_rtk:
          state_id: 0 # 0 - position, 1 - velocity, 2 - acceleration
          noise: 1.0 # measurement noise covariance (R)
          noise_unhealthy_coeff: 1000.0 # covariance gets multiplied by this coefficient when correction is unhealthy (R)
          message:
            type: "mrs_msgs/RtkGps"
            topic: "hw_api/rtk" # without uav namespace
            limit: 
              delay: 0.5 # [s] messages with higher delay will flag correction as unhealthy
              time_since_last: 1.0 # [s] larger time step between messages will flag correction as unhealthy

          processors: ["saturate"] # types of processors attached to this measurement

          # median_filter:
          #   buffer_size: 100 # [samples] number of historic values from which the median is calculated
          #   max_diff: 0.5 # [m] difference of input value from median to be considered valid

          saturate:
            start_enabled: true # saturate processor can start as disabled and then be enabled by a service or a trigger condition
            keep_enabled: true # keep enabled even after the corrections are near the value of state
            min: -0.2
            max: 0.2
            limit: 1.0

        vel_hw_api:
          state_id: 1 # 0 - position, 1 - velocity, 2 - acceleration
          noise: 1.0 # measurement noise covariance (R)
          noise_unhealthy_coeff: 100.0 # covariance gets multiplied by this coefficient when correction is unhealthy (R)
          message:
            type: "geometry_msgs/Vector3Stamped"
            topic: "hw_api/velocity" # without uav namespace
            limit: 
              delay: 1.0 # [s] messages with higher delay will flag correction as unhealthy
              time_since_last: 0.5 # [s] larger time step between messages will flag correction as unhealthy

          processors: [] # types of processors attached to this measurement
