# passthrough estimator - no estimation on its own
rtk: # namespace of the state estimator
  hdg_mavros: # namespace of the heading estimator

    max_flight_altitude_agl: 100.0 # [m] maximum allowed flight altitude AGL (Above Ground Level)

    message:
      topic: "mavros/local_position/odom" # without uav namespace
