rtk: # namespace of the state estimator
  requires: # data required from the hw api
    gnss: false
    imu: false
    distance_sensor: false
    altitude: false
    magnetometer_heading: false
    position: false
    orientation: true
    velocity: true
    angular_velocity: false

  topics:
    orientation: "hw_api/orientation" # orientation passthrough
    angular_velocity: "hw_api/angular_velocity" # angular velocity passthrough



