passthrough:
  max_flight_z: 100.0 # [m] maximum allowed flight Z (in the estimator frame)

  message:
    topic: "hw_api/odometry"

  requires: # data required from the hw api
    gnss: false
    rtk: false
    imu: false
    distance_sensor: false
    altitude: false
    magnetometer_heading: false
    position: false
    orientation: false
    velocity: false
    angular_velocity: false
    ground_truth: false
    odometry: true
